swagger: '2.0'
info:
  version: 0.0.1
  title: photobooth API
host: localhost
basePath: /api
schemes:
  - http
  - https
paths:
  /targets/bluetooth/:
    post:
      tags:
        - Registration
      summary: Request user registration
      operationId: registerUser
      produces:
        - application/json
      consumes:
        - application/json
      parameters:
        - in: body
          name: user
          description: The user to create.
          required: true
          schema:
            $ref: '#/definitions/Login'
      responses:
        '201':
          description: Created
          schema:
            $ref: '#/definitions/Login'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Login'
  '/auth/reg/{token}':
    parameters:
      - in: path
        name: token
        type: string
        required: true
        description: The email confirmation token.
    put:
      tags:
        - Registration
      summary: Complete user registration
      operationId: registerUserCompletion
      produces:
        - application/json
      responses:
        '200':
          description: Operation successfull
          schema:
            $ref: '#/definitions/Login'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Login'
parameters:
  limitParam:
    name: limit
    in: query
    type: integer
    description: Limit the number of items to given amount
  startParam:
    name: start
    in: query
    type: integer
    description: Return the list items starting from this offset
definitions:
  bluetooth_device:
    type: object
    required:
      - address
      - name
    properties:
      address          :
        type: string
        example: "04:5D:4B:5F:79:10"
      alias            :
        type: string
        example: "MDR-1000X"
      paired             :
        type: bool
        example: true
      icon             :
        type: string
        example: "printer"
      modalias         :
        type: string
        example: ""
      name             :
        type: string
        example: "MDR-1000X"
